application: endurance-176900
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /icon1\.jpeg
  static_files: images/icon1.jpeg
  upload: icon1\.jpeg
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /
  script: main.app
  login: required
- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
