application: endurance
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /styles
  static_dir: styles
<<<<<<< HEAD
- url: /scripts
  static_dir: scripts
=======
- url: /
  script: main.app
  login: required
>>>>>>> a36689d7ecf10a80be2a3d6d2325f6ecc5680c60
- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
