application: endurance-176900
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.jpeg
  static_files: images/favicon.jpeg
  upload: favicon\.jpeg
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /
  script: main.app
  login: required
- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
